<?php

namespace AppBundle\Repository;

/**
 * NumeroPanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignePanierRepository extends \Doctrine\ORM\EntityRepository
{
}
